include:
  - ./compose.services.yml
  - ./compose.databases.yml

volumes:
  db-gateway:
  db-product:
  db-cart:
  
networks:
  network-services:
  network-product:
  network-cart:
  network-gateway:
  network-redis: