services:
  ### SERVICES ###
  api-gateway:
    build:
      context: ./api-gateway
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      product:
        condition: service_started
      cart:
        condition: service_started
      redis:
        condition: service_started
      db-gateway:
        condition: service_healthy
    networks:
      - network-services
      - network-gateway
      - network-redis

  product:
    build:
      context: ./product
    volumes:
      - ./product:/app
      - /app/node_modules
    ports:
      - 3001:3000
    depends_on:
      db-product:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - network-services
      - network-product
      - network-redis

  cart:
    build:
      context: ./cart
    volumes:
      - ./cart:/app
      - /app/node_modules
    ports:
      - 3002:3000
    depends_on:
      db-cart:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - network-services
      - network-cart
      - network-redis


  ### DATABASES ###
  db-gateway:
    image: postgres:latest
    env_file:
      - ./api-gateway/.env
    volumes:
      - db-gateway:/var/lib/postgresql/data
      - ./db/gateway.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - network-gateway
      - network-redis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  db-product:
    image: postgres:latest
    env_file:
      - ./product/.env
    volumes:
      - db-gateway:/var/lib/postgresql/data
      - ./db/product.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - network-product
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-cart:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null  
    env_file:
      - ./cart/.env
    volumes: 
      - db-cart:/data/db
      - ./cart.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - network-cart
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    networks:
      - network-redis



volumes:
  db-gateway:
  db-product:
  db-cart:

networks:
  network-services:
  network-product:
  network-cart:
  network-gateway:
  network-redis: