POST http://localhost:3000/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOjEsImlhdCI6MTc0MDY1MDk2NX0.5jG9I0eTZPC_2dkomy4GHni3OvcPga-JyUyKK8cGtbI

{
    "name": "Product new",
    "price": 10.5,
    "description": "Product description",
    "in_stock": true
}