POST http://localhost:3000/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOjEsImlhdCI6MTc0MDc0MDc1N30.O46U0Qr5BCfzDoK1eaYotj1zpvlYf0EezJXs49iucRs

{
    "name": "Product new",
    "price": 10.5,
    "description": "Product description",
    "in_stock": true
}