PUT http://localhost:3000/products/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOjEsImlhdCI6MTc0MDc0NTIxM30.2yE6e1BFNwTVDa8UkmnCxH-bos0oUqepQFS9Z0m6hCg

{
    "name": "Product updated",
    "price": 20.5,
    "description": "Product description updated",
    "in_stock": false
}