PUT http://localhost:3000/carts/clients/1/products/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOjEsImlhdCI6MTc0MDc0MDc1N30.O46U0Qr5BCfzDoK1eaYotj1zpvlYf0EezJXs49iucRs

{
    "quantity": 7
}